DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TRAIN_U:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

OPTIM:
  NAME: "adam"
  LR: 3e-3
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 1e-5

OPTIM_C:
  NAME: "adam"
  LR: 3e-3
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "linear"
  WARMUP_MIN_LR: 1e-5

TRAIN:
  PRINT_FREQ: 100

TRAINER:
  DAMP:
    PREC: "amp"
    N_CTX: 32
    N_CLS: 2
    TAU: 0.5
    U: 1.0


