INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "normalize"]

DATASET:
  NAME: "OfficeHome"
  SOURCE_DOMAINS: ["real_world"]
  # TARGET_DOMAINS: ["art"]
  TARGET_DOMAINS: ["clipart"]
  # TARGET_DOMAINS: ["product"]
  # TARGET_DOMAINS: ["real_world"]
# you can modify the code to explore four domains

TRAINER:
  DAMP:
    STRONG_TRANSFORMS: ["random_flip", "randaugment", "normalize"]

MODEL:
  BACKBONE:
    NAME: "RN50"
